# Generated by Django 4.2 on 2023-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='False', default='images\\default-profile-pic.jpg', upload_to='images/'),
        ),
    ]
