# Generated by Django 4.2 on 2023-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='False', default='media/default-profile-pic.jpg', upload_to='media/'),
        ),
    ]
