# Generated by Django 4.2 on 2023-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='toemail',
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
