# Generated by Django 4.2 on 2023-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_messages_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='send_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
